### ISSUE TITLE
RuntimeError in loading model for evaluation

### ISSUE THREAD

**Issue by y5wang** [daveredrum/Pointnet2.ScanNet#5]
When trying to run `eval.py` with a newly trained model, I ran into this RuntimeError when loading state_dict for Pointnet2MSG. My environment is:
- Ubuntu 18.04
- Python 3.7.6
- PyTorch 1.4 with CUDA 10.1
- GeForce RTX 2070 GPU

The training is done as:
```python train.py --batch_size 32 --epoch 500 --lr 1e-3 --verbose 10 --weighting```

When I ran eval as:
```python eval.py --batch_size 32 --folder 2020-03-10_16-32-57_CUDA_WL```
I got the error:
```preparing data...
loading model...
Traceback (most recent call last):
  File "eval.py", line 233, in <module>
    evaluate(args)
  File "eval.py", line 185, in evaluate
    model.load_state_dict(torch.load(model_path))
  File "/home/yang/Anaconda3/envs/pn2.scannet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Pointnet2MSG:
	Missing key(s) in state_dict: "SA_modules.0.mlps.1.layer0.conv.weight", "SA_modules.0.mlps.1.layer0.bn.bn.weight", "SA_modules.0.mlps.1.layer0.bn.bn.bias", "SA_modules.0.mlps.1.layer0.bn.bn.running_mean", "SA_modules.0.mlps.1.layer0.bn.bn.running_var", "SA_modules.0.mlps.1.layer1.conv.weight", "SA_modules.0.mlps.1.layer1.bn.bn.weight", "SA_modules.0.mlps.1.layer1.bn.bn.bias", "SA_modules.0.mlps.1.layer1.bn.bn.running_mean", "SA_modules.0.mlps.1.layer1.bn.bn.running_var", "SA_modules.0.mlps.1.layer2.conv.weight", "SA_modules.0.mlps.1.layer2.bn.bn.weight", "SA_modules.0.mlps.1.layer2.bn.bn.bias", "SA_modules.0.mlps.1.layer2.bn.bn.running_mean", "SA_modules.0.mlps.1.layer2.bn.bn.running_var", "SA_modules.1.mlps.1.layer0.conv.weight", "SA_modules.1.mlps.1.layer0.bn.bn.weight", "SA_modules.1.mlps.1.layer0.bn.bn.bias", "SA_modules.1.mlps.1.layer0.bn.bn.running_mean", "SA_modules.1.mlps.1.layer0.bn.bn.running_var", "SA_modules.1.mlps.1.layer1.conv.weight", "SA_modules.1.mlps.1.layer1.bn.bn.weight", "SA_modules.1.mlps.1.layer1.bn.bn.bias", "SA_modules.1.mlps.1.layer1.bn.bn.running_mean", "SA_modules.1.mlps.1.layer1.bn.bn.running_var", "SA_modules.1.mlps.1.layer2.conv.weight", "SA_modules.1.mlps.1.layer2.bn.bn.weight", "SA_modules.1.mlps.1.layer2.bn.bn.bias", "SA_modules.1.mlps.1.layer2.bn.bn.running_mean", "SA_modules.1.mlps.1.layer2.bn.bn.running_var", "SA_modules.2.mlps.1.layer0.conv.weight", "SA_modules.2.mlps.1.layer0.bn.bn.weight", "SA_modules.2.mlps.1.layer0.bn.bn.bias", "SA_modules.2.mlps.1.layer0.bn.bn.running_mean", "SA_modules.2.mlps.1.layer0.bn.bn.running_var", "SA_modules.2.mlps.1.layer1.conv.weight", "SA_modules.2.mlps.1.layer1.bn.bn.weight", "SA_modules.2.mlps.1.layer1.bn.bn.bias", "SA_modules.2.mlps.1.layer1.bn.bn.running_mean", "SA_modules.2.mlps.1.layer1.bn.bn.running_var", "SA_modules.2.mlps.1.layer2.conv.weight", "SA_modules.2.mlps.1.layer2.bn.bn.weight", "SA_modules.2.mlps.1.layer2.bn.bn.bias", "SA_modules.2.mlps.1.layer2.bn.bn.running_mean", "SA_modules.2.mlps.1.layer2.bn.bn.running_var", "SA_modules.3.mlps.1.layer0.conv.weight", "SA_modules.3.mlps.1.layer0.bn.bn.weight", "SA_modules.3.mlps.1.layer0.bn.bn.bias", "SA_modules.3.mlps.1.layer0.bn.bn.running_mean", "SA_modules.3.mlps.1.layer0.bn.bn.running_var", "SA_modules.3.mlps.1.layer1.conv.weight", "SA_modules.3.mlps.1.layer1.bn.bn.weight", "SA_modules.3.mlps.1.layer1.bn.bn.bias", "SA_modules.3.mlps.1.layer1.bn.bn.running_mean", "SA_modules.3.mlps.1.layer1.bn.bn.running_var", "SA_modules.3.mlps.1.layer2.conv.weight", "SA_modules.3.mlps.1.layer2.bn.bn.weight", "SA_modules.3.mlps.1.layer2.bn.bn.bias", "SA_modules.3.mlps.1.layer2.bn.bn.running_mean", "SA_modules.3.mlps.1.layer2.bn.bn.running_var". 
	size mismatch for SA_modules.0.mlps.0.layer0.conv.weight: copying a param with shape torch.Size([32, 9, 1, 1]) from checkpoint, the shape in current model is torch.Size([16, 9, 1, 1]).
	size mismatch for SA_modules.0.mlps.0.layer0.bn.bn.weight: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for SA_modules.0.mlps.0.layer0.bn.bn.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for SA_modules.0.mlps.0.layer0.bn.bn.running_mean: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for SA_modules.0.mlps.0.layer0.bn.bn.running_var: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for SA_modules.0.mlps.0.layer1.conv.weight: copying a param with shape torch.Size([32, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([16, 16, 1, 1]).
	size mismatch for SA_modules.0.mlps.0.layer1.bn.bn.weight: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for SA_modules.0.mlps.0.layer1.bn.bn.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for SA_modules.0.mlps.0.layer1.bn.bn.running_mean: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for SA_modules.0.mlps.0.layer1.bn.bn.running_var: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for SA_modules.0.mlps.0.layer2.conv.weight: copying a param with shape torch.Size([64, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([32, 16, 1, 1]).
	size mismatch for SA_modules.0.mlps.0.layer2.bn.bn.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for SA_modules.0.mlps.0.layer2.bn.bn.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for SA_modules.0.mlps.0.layer2.bn.bn.running_mean: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for SA_modules.0.mlps.0.layer2.bn.bn.running_var: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for SA_modules.1.mlps.0.layer0.conv.weight: copying a param with shape torch.Size([64, 67, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 99, 1, 1]).
	size mismatch for SA_modules.2.mlps.0.layer0.conv.weight: copying a param with shape torch.Size([128, 131, 1, 1]) from checkpoint, the shape in current model is torch.Size([128, 259, 1, 1]).
	size mismatch for SA_modules.2.mlps.0.layer1.conv.weight: copying a param with shape torch.Size([128, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([196, 128, 1, 1]).
	size mismatch for SA_modules.2.mlps.0.layer1.bn.bn.weight: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([196]).
	size mismatch for SA_modules.2.mlps.0.layer1.bn.bn.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([196]).
	size mismatch for SA_modules.2.mlps.0.layer1.bn.bn.running_mean: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([196]).
	size mismatch for SA_modules.2.mlps.0.layer1.bn.bn.running_var: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([196]).
	size mismatch for SA_modules.2.mlps.0.layer2.conv.weight: copying a param with shape torch.Size([256, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 196, 1, 1]).
	size mismatch for SA_modules.3.mlps.0.layer0.conv.weight: copying a param with shape torch.Size([256, 259, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 515, 1, 1]).
	size mismatch for FP_modules.0.mlp.layer0.conv.weight: copying a param with shape torch.Size([128, 134, 1, 1]) from checkpoint, the shape in current model is torch.Size([128, 262, 1, 1]).
	size mismatch for FP_modules.1.mlp.layer0.conv.weight: copying a param with shape torch.Size([256, 320, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 608, 1, 1]).
	size mismatch for FP_modules.1.mlp.layer1.conv.weight: copying a param with shape torch.Size([128, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 256, 1, 1]).
	size mismatch for FP_modules.1.mlp.layer1.bn.bn.weight: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for FP_modules.1.mlp.layer1.bn.bn.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for FP_modules.1.mlp.layer1.bn.bn.running_mean: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for FP_modules.1.mlp.layer1.bn.bn.running_var: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for FP_modules.2.mlp.layer0.conv.weight: copying a param with shape torch.Size([256, 384, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 768, 1, 1]).
	size mismatch for FP_modules.2.mlp.layer0.bn.bn.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for FP_modules.2.mlp.layer0.bn.bn.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for FP_modules.2.mlp.layer0.bn.bn.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for FP_modules.2.mlp.layer0.bn.bn.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for FP_modules.2.mlp.layer1.conv.weight: copying a param with shape torch.Size([256, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 512, 1, 1]).
	size mismatch for FP_modules.2.mlp.layer1.bn.bn.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for FP_modules.2.mlp.layer1.bn.bn.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for FP_modules.2.mlp.layer1.bn.bn.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for FP_modules.2.mlp.layer1.bn.bn.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for FP_modules.3.mlp.layer0.conv.weight: copying a param with shape torch.Size([256, 768, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 1536, 1, 1]).
	size mismatch for FP_modules.3.mlp.layer0.bn.bn.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for FP_modules.3.mlp.layer0.bn.bn.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for FP_modules.3.mlp.layer0.bn.bn.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for FP_modules.3.mlp.layer0.bn.bn.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for FP_modules.3.mlp.layer1.conv.weight: copying a param with shape torch.Size([256, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 512, 1, 1]).
	size mismatch for FP_modules.3.mlp.layer1.bn.bn.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for FP_modules.3.mlp.layer1.bn.bn.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for FP_modules.3.mlp.layer1.bn.bn.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for FP_modules.3.mlp.layer1.bn.bn.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
```

Any help is appreciated... @daveredrum

**Comment by daveredrum** [comment]
Hey @y5wang, i've solved this issue you've encountered. it might be related with the missing MSG flags in the `eval.py`, because it's switched off in `train.py`and on in `eval.py` by default, respectively.  could you please pull and try out the code again to see if the problem persists?

**Comment by daveredrum** [comment]
Should be fixed now.
